# -*- coding: utf-8 -*-
"""resume analyser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162hGmzYIla4mD3P0Zc73j8ffY10wt6d_
"""


# importing required modules
from ast import pattern
from pypdf import PdfReader
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab')
from nltk.corpus import stopwords
import re
from fuzzywuzzy import fuzz
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import collections
import numpy as np
import pandas as pd
import matplotlib.cm as cm
import matplotlib.pyplot as plt
from matplotlib import colors, rcParams, text
from wordcloud import WordCloud, STOPWORDS



class ResumeAnalyzer:
    def __init__(self, pdf_path=None):
        self.pdf_path = pdf_path
        self.text = self.collect_pdf_text(pdf_path) if pdf_path else ""
        self.tokens = self.tokenize_text(self.text) if self.text else []
        self.word_count = self.count_words(self.text) if self.text else 0
        self.sentence_count = self.count_sentences(self.text) if self.text else 0
        self.preprocessed_text = self.preprocess_text_remove_stopwords(self.text) if self.text else ""
        self.education_pattern = r'EDUCATION\s*(.*?)(?:TECHNICAL\s+SKILLS|RELEVANT\s+EXPERIENCE|PROJECTS|LEADERSHIP\s+EXPERIENCE|$)'
        self.experience_pattern = r'RELEVANT\s+EXPERIENCE\s*(.*?)(?:TECHNICAL\s+SKILLS|EDUCATION|PROJECTS|LEADERSHIP\s+EXPERIENCE|$)'
        self.common_skills_fuzzy = [
                    "Python", "Machine Learning", "TensorFlow", "Docker", "NLP", "Natural Language Processing",
                    "Java", "C++", "JavaScript", "React", "Angular", "Vue.js", "Vue",
                    "SQL", "NoSQL", "AWS", "Amazon Web Services", "Azure", "Microsoft Azure", "Google Cloud Platform", "GCP",
                    "Data Analysis", "Data Science", "Deep Learning", "Computer Vision",
                    "Git", "GitHub", "Agile", "Scrum", "Project Management", "Communication",
                    "Problem Solving", "Critical Thinking", "Data Structures", "Algorithms", "Web Development"
]
        self.job_description_skills = [
                    "Python", "Java", "AWS", "Docker", "SQL", "Machine Learning",
                    "Agile", "Communication", "Project Management", "Leadership",
                    "Data Analysis", "React", "Angular", "TensorFlow", "GCP"
]

    def collect_pdf_text(self, pdf_path):
        reader = PdfReader(pdf_path)
        text = ""
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
        return text

    def extract_text_from_file(self, file_stream):
        """Extract text from an uploaded PDF file-like object (all pages)."""
        reader = PdfReader(file_stream)
        text = ""
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
        return text

    def tokenize_text(self, text):
        tokens = word_tokenize(text)
        return tokens

    def count_words(self, text):
        tokens = self.tokenize_text(text)
        return len(tokens)

    def count_sentences(self, text):
        sentences = nltk.sent_tokenize(text)
        return len(sentences)

    def preprocess_text_remove_stopwords(self, text):
    # Tokenize words, convert to lowercase, and remove stopwords
        words = word_tokenize(text.lower())
        stop_words = set(stopwords.words('english'))
        filtered_words = [word for word in words if word.isalnum() and word not in stop_words]
        return ' '.join(filtered_words)
    

    def find_phone_number(self):
        pattern = r'\b(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]*\d{3}[-.\s]*\d{4}\b'
        match = re.search(pattern, self.text)
        if match:
            print(f"Phone number detected! Found: {match.group(0)}")
        else:
            print("Phone number pattern not detected.")


    def find_email(self):
        pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
        match = re.search(pattern, self.text)
        if match:
            print(f"Email detected! Found: {match.group(0)}")
        else:
            print("Email pattern not detected.")


    def extract_skills_with_fuzzy_matching(self, text, skills_list, threshold=80):
        found_skills = set()
        text_lower = text.lower()
        words_in_text = text_lower.split()

        for skill_item in skills_list:
            skill_lower = skill_item.lower()

            # 1. Exact word-boundary match
            if re.search(r'\b' + re.escape(skill_lower) + r'\b', text_lower):
                found_skills.add(skill_item)
                continue

            # 2. Fuzzy match against single words
            if any(fuzz.ratio(skill_lower, word_in_text) >= threshold for word_in_text in words_in_text):
                found_skills.add(skill_item)
                continue

            # 3. Fuzzy match against short phrases (up to 3 words)
            matched = False
            for i in range(len(words_in_text)):
                for j in range(i + 1, min(i + 4, len(words_in_text) + 1)):
                    phrase_in_text = ' '.join(words_in_text[i:j])
                    if fuzz.ratio(skill_lower, phrase_in_text) >= threshold:
                        found_skills.add(skill_item)
                        matched = True
                        break
                if matched:
                    break

        return sorted(list(found_skills))

  
    
    def calculate_skill_match_score(self, resume_skills, job_skills):

    # Convert skills to sets for efficient intersection calculation
        resume_skills_set = set(skill.lower() for skill in resume_skills)
        job_skills_set = set(skill.lower() for skill in job_skills)

    # Find common skills
        common_skills = resume_skills_set.intersection(job_skills_set)

    # Calculate the score
        if not job_skills_set:
            return 0.0 # Avoid division by zero if there are no job skills

    # Score is the percentage of job skills found in the resume
        match_score = (len(common_skills) / len(job_skills_set)) * 100
        return match_score
    

    def find_education_and_experience_sections(self):
    # Define patterns for Education and Experience sections
        education_pattern = r'EDUCATION\s*(.*?)(?:TECHNICAL\s+SKILLS|RELEVANT\s+EXPERIENCE|PROJECTS|LEADERSHIP\s+EXPERIENCE|$)'
        experience_pattern = r'RELEVANT\s+EXPERIENCE\s*(.*?)(?:TECHNICAL\s+SKILLS|EDUCATION|PROJECTS|LEADERSHIP\s+EXPERIENCE|$)'

    # Extract Education section
        education_match = re.search(education_pattern, self.text, re.DOTALL | re.IGNORECASE)
        education_section = education_match.group(1).strip() if education_match else "Not found"

    # Extract Experience section
        experience_match = re.search(experience_pattern, self.text, re.DOTALL | re.IGNORECASE)
        experience_section = experience_match.group(1).strip() if experience_match else "Not found"

        return education_section, experience_section



    def generate_wordcloud_and_bar_chart(self,resume):

        wordcloud = WordCloud(stopwords=stopwords, background_color="white", max_words=1000).generate(text)
        rcParams['figure.figsize'] = 10, 20
        plt.imshow(wordcloud)
        plt.axis("off")
        plt.show()
        filtered_words = [word for word in resume.split() if word not in stopwords]
        counted_words = collections.Counter(filtered_words)
        words = []
        counts = []
        for letter, count in counted_words.most_common(10):
            words.append(letter)
            counts.append(count)
        colors = cm.rainbow(np.linspace(0, 1, 10))
        rcParams['figure.figsize'] = 20, 10
        plt.title('Top words in the headlines vs their count')
        plt.xlabel('Count')
        plt.ylabel('Words')
        plt.barh(words, counts, color=colors)
        plt.show()


    def cosine_similarity_analysis(self,resume_text, job_description_text):
        # Initialize TF-IDF Vectorizer (will be refit for each request)
    
        vectorizer = TfidfVectorizer()
        tfidf_matrix = vectorizer.fit_transform([self.text, job_description_text])

        # The first row of tfidf_matrix is the resume vector, the second is the job description vector
        resume_tfidf_vector = tfidf_matrix[0:1]
        job_description_tfidf_vector = tfidf_matrix[1:2]

        # Calculate cosine similarity
        cosine_sim = cosine_similarity(resume_tfidf_vector, job_description_tfidf_vector)[0][0]

        print(f"Resume-Job Cosine Similarity (TF-IDF): {cosine_sim:.4f}")

        preprocessed_resume_text = self.preprocess_text_remove_stopwords(self.text)
        preprocessed_job_description_text = self.preprocess_text_remove_stopwords(job_description_text)

        # Fit and transform the preprocessed texts into TF-IDF vectors
        tfidf_matrix_stopwords = vectorizer.fit_transform([preprocessed_resume_text, preprocessed_job_description_text])

        # The first row of tfidf_matrix_stopwords is the resume vector, the second is the job description vector
        resume_tfidf_vector_stopwords = tfidf_matrix_stopwords[0:1]
        job_description_tfidf_vector_stopwords = tfidf_matrix_stopwords[1:2]

        # Calculate cosine similarity with stopwords removed
        cosine_sim_stopwords = cosine_similarity(resume_tfidf_vector_stopwords, job_description_tfidf_vector_stopwords)[0][0]

        print(f"Resume-Job Cosine Similarity (TF-IDF, Stopwords Removed): {cosine_sim_stopwords:.4f}")

